name: Frends.AMQP.Send Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.AMQP.Send/**'
  workflow_dispatch:
  
jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.AMQP.Send
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}