name: Frends.AMQP.Send Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.AMQP.Send/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.AMQP.Send
      prebuild_command: docker pull rmohr/activemq && docker run -d -p 5672:5672 -p 8161:8161 rmohr/activemq
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}