name: Frends.AMQP.Send Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.AMQP.Send/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.AMQP.Send
    secrets:
      env_var_value_1: ${{ secrets.AMQPS_CONN_STR }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}