name: Frends.AMQP.Send Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.AMQP.Send/**'
  workflow_dispatch:
  
jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.AMQP.Send
      prebuild_command: docker pull rmohr/activemq && docker run -d -p 5672:5672 -p 8161:8161 rmohr/activemq
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}